package lige.grupo03.pr4;

public enum TipoEvento {
	EVENTO_PARTIDA_INICIADA,EVENTO_GO,EVENTO_PARTIDA_FINALIZADA,
	EVENTO_MOVIMIENTO_REALIZADO,EVENTO_OBJETO_COGIDO,EVENTO_OBJETO_USADO,
	EVENTO_ERROR
}
